# These settings that appropriate to the currently running environment are
# accessible through the SECRETS constant, which is a Hash using symbol keys.
#
# For example: SECRETS.fetch(:rails_secret_token)
#
# When deploying to production, symlink a shared/config/secrets.yml file
# containing the production secrets into current/config/secrets.yml, just
# like you would for database.yml.
#
# This system ensures that sensitive tokens, API keys, etc. are kept out
# of source control.

development: &development
  rails_secret_token: 69560e72e3063ee6399dd6976b4a0fed3ffdb7c3065adbd911e5868c8600953c4743cbd93cf95d33b480824af966aa2ad847eec9040b6be98062e25edff3f442

test:
  <<: *development
