# These settings that appropriate to the currently running environemnt are
# accessible through the SECRETS constant.
#
# For example: SECRETS[:rails_secret_token]
#
# When deploying to production, symlink a shared/config/secrets.yml file
# containing the production secrets into current/config/secrets.yml, just
# like you would for database.yml.
#
# This system ensures that sensitive tokens, API keys, etc. are kept out
# of source control.

development: &development
  rails_secret_key_base: 30dc007d4ad912fe9d4e385c55c79bc6fa2ab4877c3de73a4b0e94933dd9e06abd44116121e3d9039af504ebdc3fcc7d8c098d8b1b51b358795839b49f31a894

test:
  <<: *development
